services:
  db:
    image: postgres:15
    container_name: postgres-accuknox
    environment:
      POSTGRES_DB: accuknox_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-accuknox
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-accuknox
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
